FROM clojure:tools-deps-1.10.1.727-slim-buster AS builder

RUN apt-get update && \
    apt-get upgrade --yes && \
    apt-get install -y curl software-properties-common && \
    curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
    apt-get install -y git zip && \
    mkdir -p /usr/share/man/man1 && \
    apt-get install -y maven && \
    apt-get install -y nodejs && \
    apt-get install -y python3-pip && \
    python3 -m pip install requests && \
    python3 -m pip install pyparsing

RUN mkdir -p /usr/src/fluree-ledger
WORKDIR /usr/src/fluree-ledger

RUN git clone --depth 1 https://github.com/fluree/ledger.git .
COPY fluree_version_patch.py /usr/src/fluree-ledger
RUN python3 ./fluree_version_patch.py
RUN clojure -A:test -Stree
RUN make

FROM python:3.9-slim-buster AS runner
WORKDIR /usr/src/fsst

COPY --from=builder /usr/src/fluree-ledger/build/fluree-*.zip /usr/src/
COPY fsst /usr/src/fsst/fsst
RUN apt-get update && \
    apt-get upgrade --yes && \
    apt-get --yes install apt-utils && \
    apt-get install --yes gcc && \
    apt-get install --yes g++ && \
    # Some extra dependencies needed because we use the "slim" python image from docker.
    apt-get --yes install libgmp-dev && \
    apt-get --yes install unzip && \
    mkdir /usr/share/man/man1 && \
    apt-get install dialog -y && \
    # Install Java (dependency for FlureeDB)
    apt-get install openjdk-11-jre-headless -y && \
    # Get the latest pip for the 3.9 version of Python
    python3 -m pip install pip --force && \
    # Dependencies of fsst tool
    python3 -m pip install base58 && \
    python3 -m pip install aioflureedb[domainapi] && \
    # Unzip the fluree zip file and remove the zip.
    cd /usr/src && \
    unzip fluree-*.zip -d fsst/ && \
    echo snapshot`date --iso-8601` >> VERSION && \
    rm fluree-*.zip && \
    # Remove stuff we no longer need.
    apt autoremove --yes && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

CMD ["/usr/src/fsst/fluree_start.sh"]
